openapi: "3.0.0"
info:
  description: Autam project
  version: 0.0.1
  title: Autam
servers:
  - url: http://localhost:8080
paths:
  /document_request_process:
    get:
      summary: List all document request process
      operationId: findAllDocumentRequestProcess
      tags:
        - document_request_process
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of document request process
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentRequestProcessList"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a Document Request Process
      tags:
        - document_request_process
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /document_request_process/{documentRequestProcessId}:
    get:
      summary: Info for a specific document request process
      operationId: findDocumentRequestProcessById
      tags:
        - document_request_process
      parameters:
        - name: documentRequestProcessId
          in: path
          required: true
          description: The id of the document request process
          schema:
            type: integer
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentRequestProcess"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    DocumentRequestProcess:
      properties:
        id:
          type: integer
          format: int64
        person:
          $ref: "#/components/schemas/Person"
    DocumentRequestProcessList:
      type: array
      items:
        $ref: "#/components/schemas/DocumentRequestProcess"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Person:
      type: object
      properties:
        id: 
          type: Long
        name:
          type: string
        surname:
          type: string 